# Netlify configuration for troyaltus.com

# Build command and publish directory
[build]
  publish = "."
  command = "quarto render"

# Redirects and rewrites
[[redirects]]
  from = "/ebook/*"
  to = "/docs/:splat"
  status = 200

# Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
